#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults
param set BAT1_SOURCE 1
param set COM_DL_LOSS_T 300
param set THR_MDL_FAC 0.000
set MIXER quad_w
