#!/bin/sh
# @name EVTOL FW Large
# @type EVTOL_FW
. ${R}etc/init.d/rc.vtol_defaults
. ${R}etc/init.d-posix/airframes/4201_custom_evtol
param set FW_THR_CRUISE 0.54
param set EKF2_ARSP_THR 1
param set EKF2_FUSE_BETA 1
param set WV_EN 1
set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
