#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

param set COM_DL_LOSS_T 100
param set NAV_FW_ALT_RAD 20
param set COM_RCL_EXCEPT 1
param set FW_L1_PERIOD 15
param set FW_MAN_P_MAX 30
param set FW_PR_FF 0.5
param set FW_PR_P 0.2
param set FW_PSP_OFF 0
param set FW_P_LIM_MAX 35
param set FW_P_LIM_MIN -35
param set FW_RR_FF 0.5
param set FW_RR_P 0.05
param set FW_THR_CRUISE 0.8
param set FW_THR_MAX 1
param set FW_THR_MIN 0.05
param set FW_T_CLMB_MAX 8
param set FW_T_SINK_MAX 2.7
param set FW_T_SINK_MIN 2.2
param set FW_P_TC 0.7
param set MIS_TAKEOFF_ALT 15
param set THR_MDL_FAC 1.000

param set MPC_XY_CRUISE 20
param set MPC_ACC_HOR_MAX 5
param set MPC_XY_P 0.95
param set MPC_XY_VEL_P_ACC 1.8
param set MPC_XY_VEL_I_ACC 0.4
param set MPC_XY_VEL_D_ACC 0.2

param set NAV_ACC_RAD 20
param set NAV_LOITER_RAD 20
param set NAV_FORCE_VT 1

param set VT_FWD_THRUST_EN 4
param set VT_F_TRANS_THR 0.8
param set VT_MOT_ID 1234
param set VT_FW_MOT_OFFID 1234
param set VT_B_TRANS_DUR 10
param set VT_TYPE 2
param set VT_PSHER_RMP_DT 2

param set MC_ROLLRATE_K 1
param set MC_ROLLRATE_D 0.0004 #0.0090
param set MC_ROLLRATE_I 0.02

param set MC_PITCHRATE_K 1
param set MC_PITCHRATE_D 0.0005 #0.0090
param set MC_PITCHRATE_I 0.02

param set MC_YAWRATE_K 1
param set MC_YAWRATE_I 0.10
param set CBRK_AIRSPD_CHK 162128
param set FW_ARSP_MODE 1
param set VT_TRANS_MIN_TM 4
param set VT_FW_PERM_STAB 1
set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
